
//更新用户信息
export const UPDATE_USERINFO = 'UPDATE_USERINFO';

//清空用户信息
export const REMOVE_USERINFO = 'REMOVE_USERINFO';

export const UPDATE_TODOLIST = 'UPDATE_TODOLIST'

export const UPDATE_MSGLIST = 'UPDATE_MSGLIST'

export const UPDATE_FRIENDSLIST = 'UPDATE_FRIENDSLIST'

export const UPDATE_USERLIST = 'UPDATE_USERLIST'

export const UPDATE_WXSIGN = 'UPDATE_WXSIGN'

export const UPDATE_WXTOKEN = 'UPDATE_WXTOKEN'
